     services:
      #  app:
      #    build: .
      #    ports:
      #      - "8080:8080"
      #    depends_on:
      #      - postgres
       postgres:
         image: postgres:latest
         environment:
           POSTGRES_USER: postgres
           POSTGRES_PASSWORD: postgres
           POSTGRES_DB: subscription_db
         ports:
           - "5432:5432"
         volumes:
           - postgres_data:/var/lib/postgresql/data
     volumes:
       postgres_data: